// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using ServiceStack.DataAnnotations;
namespace YW.Model.Entitys.YW2016
{

    /// <summary>
    /// 
    /// </summary>
    [Remark("")]
	[Alias("student_info")]
	[FromT4]
    [Serializable]
    public partial class StudentInfo : YW.Model.HasId    {

		/// <summary>  </summary>
        [Alias("id")]
        [AutoIncrement]
        public override long Id { get; set;}

		/// <summary>  </summary>
        [Alias("name")]
        [Required]
        public string Name { get; set;}

		/// <summary>  </summary>
        [Alias("age")]
        [Required]
        public int Age { get; set;}

		/// <summary>  </summary>
        [Alias("create_time")]
        [Required]
        public DateTime CreateTime { get; set;}

		/// <summary>  </summary>
        [Alias("remark")]
        public string Remark { get; set;}
    }

}
#pragma warning restore 1591
